create schema if not exists crm;

create table if not exists crm.auth_signup_contacts (
  id bigint generated by default as identity primary key,
  email text not null,
  normalized_email text generated always as (lower(btrim(email))) stored,
  site_key text not null,
  site_name text,
  country_code text,
  locale text,
  site_url text,
  source text not null default 'auth_signup',
  soft_consent boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (normalized_email, site_key)
);

create table if not exists crm.contact_consents (
  id bigint generated by default as identity primary key,
  normalized_email text not null,
  site_key text not null,
  consent_type text not null,
  consent_status text not null,
  source text not null default 'auth_signup',
  granted_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (normalized_email, site_key, consent_type)
);

create index if not exists auth_signup_contacts_site_key_idx
  on crm.auth_signup_contacts (site_key, created_at desc);

create index if not exists contact_consents_site_key_idx
  on crm.contact_consents (site_key, granted_at desc);

create or replace function public.record_auth_signup(
  p_email text,
  p_site_key text,
  p_site_name text default null,
  p_country_code text default null,
  p_locale text default null,
  p_site_url text default null
) returns void
language plpgsql
security definer
set search_path = public, crm
as $$
declare
  v_email text;
begin
  v_email := lower(btrim(coalesce(p_email, '')));

  if v_email = '' or btrim(coalesce(p_site_key, '')) = '' then
    return;
  end if;

  insert into crm.auth_signup_contacts (
    email,
    site_key,
    site_name,
    country_code,
    locale,
    site_url,
    soft_consent,
    updated_at
  ) values (
    v_email,
    p_site_key,
    p_site_name,
    p_country_code,
    p_locale,
    p_site_url,
    true,
    now()
  )
  on conflict (normalized_email, site_key) do update
    set site_name = excluded.site_name,
        country_code = excluded.country_code,
        locale = excluded.locale,
        site_url = excluded.site_url,
        soft_consent = true,
        updated_at = now();

  insert into crm.contact_consents (
    normalized_email,
    site_key,
    consent_type,
    consent_status,
    source,
    updated_at
  ) values (
    v_email,
    p_site_key,
    'news_updates',
    'soft_opt_in',
    'auth_signup',
    now()
  )
  on conflict (normalized_email, site_key, consent_type) do update
    set consent_status = excluded.consent_status,
        source = excluded.source,
        updated_at = now();
end;
$$;

grant execute on function public.record_auth_signup(text, text, text, text, text, text) to anon;
grant execute on function public.record_auth_signup(text, text, text, text, text, text) to authenticated;
grant execute on function public.record_auth_signup(text, text, text, text, text, text) to service_role;

revoke all on schema crm from public;
revoke all on all tables in schema crm from public;
