create schema if not exists crm;

create table if not exists crm.race_detail_page_views (
  id bigint generated by default as identity primary key,
  site_key text not null,
  site_name text,
  country_code text not null,
  locale text,
  domain_name text not null,
  page_path text,
  page_url text,
  referrer text,
  created_at timestamptz not null default now()
);

create index if not exists race_detail_page_views_country_created_idx
  on crm.race_detail_page_views (country_code, created_at desc);

create index if not exists race_detail_page_views_domain_created_idx
  on crm.race_detail_page_views (domain_name, created_at desc);

revoke all on crm.race_detail_page_views from public;
revoke all on crm.race_detail_page_views from anon;
revoke all on crm.race_detail_page_views from authenticated;

create or replace function public.record_race_detail_page_view(
  p_site_key text default null,
  p_site_name text default null,
  p_country_code text default null,
  p_locale text default null,
  p_domain_name text default null,
  p_page_path text default null,
  p_page_url text default null,
  p_referrer text default null
) returns void
language plpgsql
security definer
set search_path = public, crm
as $$
begin
  if btrim(coalesce(p_site_key, '')) = '' then
    return;
  end if;

  if btrim(coalesce(p_country_code, '')) = '' then
    return;
  end if;

  if btrim(coalesce(p_domain_name, '')) = '' then
    return;
  end if;

  insert into crm.race_detail_page_views (
    site_key,
    site_name,
    country_code,
    locale,
    domain_name,
    page_path,
    page_url,
    referrer
  ) values (
    p_site_key,
    nullif(btrim(coalesce(p_site_name, '')), ''),
    lower(btrim(p_country_code)),
    nullif(lower(btrim(coalesce(p_locale, ''))), ''),
    lower(btrim(p_domain_name)),
    nullif(btrim(coalesce(p_page_path, '')), ''),
    nullif(btrim(coalesce(p_page_url, '')), ''),
    nullif(btrim(coalesce(p_referrer, '')), '')
  );
end;
$$;

grant execute on function public.record_race_detail_page_view(
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text
) to anon;

grant execute on function public.record_race_detail_page_view(
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text
) to authenticated;

grant execute on function public.record_race_detail_page_view(
  text,
  text,
  text,
  text,
  text,
  text,
  text,
  text
) to service_role;

create or replace function public.get_race_detail_page_view_rankings(
  p_country_code text,
  p_days integer default 30,
  p_limit integer default 100
) returns table (
  domain_name text,
  page_views_last_30_days bigint,
  last_view_at timestamptz
)
language sql
stable
security definer
set search_path = public, crm
as $$
with normalized as (
  select
    nullif(lower(btrim(coalesce(p_country_code, ''))), '') as country_code,
    greatest(coalesce(p_days, 30), 1) as day_count,
    least(greatest(coalesce(p_limit, 100), 1), 5000) as row_limit
)
select
  views.domain_name,
  count(*)::bigint as page_views_last_30_days,
  max(views.created_at) as last_view_at
from
  crm.race_detail_page_views views
  cross join normalized
where
  normalized.country_code is not null
  and views.country_code = normalized.country_code
  and views.created_at >= now() - make_interval(days => normalized.day_count)
group by
  views.domain_name
order by
  page_views_last_30_days desc,
  last_view_at desc,
  views.domain_name asc
limit (
  select
    row_limit
  from
    normalized
);
$$;

revoke all on function public.get_race_detail_page_view_rankings(text, integer, integer) from public;
revoke all on function public.get_race_detail_page_view_rankings(text, integer, integer) from anon;
revoke all on function public.get_race_detail_page_view_rankings(text, integer, integer) from authenticated;

grant execute on function public.get_race_detail_page_view_rankings(text, integer, integer) to service_role;
